# Fibonacci Sequence - Implementation
- Course: ***UCSD Data Structure and Algorithm Specialization - Course 1: Algorithm Toolbox***
- Resource: *Learning Algorithms Through Programming and Puzzle Solving PDF*
- Note: **Use this template, or improve this template, for future algorithm implementation practice.**
---
## Problem Statement/s
Compute the n-th Fibonacci number.
- **Specifications**
    - **Input:** An integer n.
    - **Output:** n-th Fibonacci number.
- **Formatting**
    - **Input:** An integer n
    - **Output:** $F_n$
    - **Constraints:** $ 0 \leq n \leq 45$
### Compute for:
$$F_n = F_{n-1} + F_{n-2} $$
### Considerations:
- I'm using other python libraries, such as Numpy, to develop my skills in using them.
- I'm also using other python techniques. This is my deviation from the original instructions from the resource.
- I'm also adding my own annotations for learning, reviewing, and retention.


In [69]:
# Fibonacci Number: Recursive Algorithm
import numpy as np
import time

# Dashboard
num = 10

# Recursive function
def Fibonacci(n):
    if n <= 1:
        return n
    else:
        return Fibonacci(float(n)-2.) + Fibonacci(float(n)-1.)

# Time your algorithm
start_time = time.time()

# Place the code here to be timed:
print(f' The {num}th Fibonacci number is: {Fibonacci(num)}')

end_time = time.time()
diff = end_time - start_time
print(f' Code execution time is: {diff*1000} ms')

# Create a for loop to generate multiple tests:
start_time = time.time()

# Place the code here to be timed:

print(f' Multiple Tests: ')
np.random.seed(5)
fibo_num_array = np.random.randint(2,10, 5).astype(float)
print(fibo_num_array)
for i in range(len(fibo_num_array)):
    print(f' The {fibo_num_array[i]}th Fibonacci number is: {Fibonacci(fibo_num_array[i])}')

end_time = time.time()
diff = end_time - start_time
print(f' Code execution time is: {diff*1000} ms')

 The 10th Fibonacci number is: 55.0
 Code execution time is: 0.0 ms
 Multiple Tests: 
[5. 8. 9. 7. 8.]
 The 5.0th Fibonacci number is: 5.0
 The 8.0th Fibonacci number is: 21.0
 The 9.0th Fibonacci number is: 34.0
 The 7.0th Fibonacci number is: 13.0
 The 8.0th Fibonacci number is: 21.0
 Code execution time is: 0.9992122650146484 ms


In [68]:
# Fibonacci Number: List Implementation (Faster)
import numpy as np
import time

# Dashboard
num = 10

# List implementation
def Fibonacci(n):
    sequence = [0, 1]
    while len(sequence) < n+1:
        sequence.append(sequence[-1] + sequence[-2])
    return sequence[-1]
    
# Time your algorithm
start_time = time.time()

# Place the code here to be timed:
print(f' The {num}th Fibonacci number is: {Fibonacci(num)}')

end_time = time.time()
diff = end_time - start_time
print(f' Code execution time is: {diff*1000} ms')

# Create a for loop to generate multiple tests:
start_time = time.time()

# Place the code here to be timed:

print(f' Multiple Tests: ')
np.random.seed(5)
fibo_num_array = np.random.randint(2,10, 5).astype(float)
print(fibo_num_array)
for i in range(len(fibo_num_array)):
    print(f' The {fibo_num_array[i]}th Fibonacci number is: {Fibonacci(fibo_num_array[i])}')

end_time = time.time()
diff = end_time - start_time
print(f' Code execution time is: {diff*1000} ms')

 The 10th Fibonacci number is: 55
 Code execution time is: 0.0 ms
 Multiple Tests: 
[5. 8. 9. 7. 8.]
 The 5.0th Fibonacci number is: 5
 The 8.0th Fibonacci number is: 21
 The 9.0th Fibonacci number is: 34
 The 7.0th Fibonacci number is: 13
 The 8.0th Fibonacci number is: 21
 Code execution time is: 1.9981861114501953 ms


In [71]:
# Fibonacci Number: Tuple Unpacking, Multiple Assignment (Faster)
import numpy as np
import time

# Dashboard
num = 10

# Multiple Assignment
def Fibonacci(n):
    a, b = 0, 1
    i = 0
    while i < n:
        a, b = b, a + b
        i+=1
    return a
    
# Time your algorithm
start_time = time.time()

# Place the code here to be timed:
print(f' The {num}th Fibonacci number is: {Fibonacci(num)}')

end_time = time.time()
diff = end_time - start_time
print(f' Code execution time is: {diff*1000} ms')

# Create a for loop to generate multiple tests:
start_time = time.time()

# Place the code here to be timed:

print(f' Multiple Tests: ')
np.random.seed(5)
fibo_num_array = np.random.randint(2,10, 5).astype(float)
print(fibo_num_array)
for i in range(len(fibo_num_array)):
    print(f' The {fibo_num_array[i]}th Fibonacci number is: {Fibonacci(fibo_num_array[i])}')

end_time = time.time()
diff = end_time - start_time
print(f' Code execution time is: {diff*1000} ms')

 The 10th Fibonacci number is: 55
 Code execution time is: 0.9992122650146484 ms
 Multiple Tests: 
[5. 8. 9. 7. 8.]
 The 5.0th Fibonacci number is: 5
 The 8.0th Fibonacci number is: 21
 The 9.0th Fibonacci number is: 34
 The 7.0th Fibonacci number is: 13
 The 8.0th Fibonacci number is: 21
 Code execution time is: 0.0 ms


# Last Digit of Fibonacci Number
- Course: ***UCSD Data Structure and Algorithm Specialization - Course 1: Algorithm Toolbox***
- Resource: *Learning Algorithms Through Programming and Puzzle Solving PDF*
- Note: **Use this template, or improve this template, for future algorithm implementation practice.**
---
## Problem Statement/s
Compute the last digit of the nth Fibonacci number.
- **Specifications**
    - **Input:** An integer n.
    - **Output:** last digit of n-th Fibonacci number.
- **Formatting**
    - **Input:** An integer n
    - **Output:** last digit of $F_n$
    - **Constraints:** $ 0 \leq n \leq 10^6$
### Compute for:
$$F_n = \mathrm{lastdigit}[F_{n-1} + F_{n-2}] $$
### Considerations:
- I'm using other python libraries, such as Numpy, to develop my skills in using them.
- I'm also using other python techniques. This is my deviation from the original instructions from the resource.
- I'm also adding my own annotations for learning, reviewing, and retention.


In [10]:
# Last Digit of Fibonacci Number: List Implementation (Faster)
import numpy as np
import time
import sys

# Increase integer string conversion
sys.set_int_max_str_digits(1000000)

# Dashboard
num = 91239 # num = 100000 cannot be computed fast, beyond 5 secs

# List implementation
def Fibonacci(n):
    sequence = [0, 1]
    while len(sequence) < n+1:
        sequence.append(sequence[-1] + sequence[-2])
    return str(sequence[-1])[-1]
    
# Time your algorithm
start_time = time.time()

# Place the code here to be timed:
print(f' The last number of {num}th Fibonacci number is: {Fibonacci(num)}')

end_time = time.time()
diff = end_time - start_time
print(f' Code execution time is: {diff*1000} ms')

# Create a for loop to generate multiple tests:
start_time = time.time()

# Place the code here to be timed:

print(f' Multiple Tests: ')
np.random.seed(5)
fibo_num_array = np.random.randint(2,10, 5).astype(float)
print(fibo_num_array)
for i in range(len(fibo_num_array)):
    print(f' The last digit of {fibo_num_array[i]}th Fibonacci number is: {Fibonacci(fibo_num_array[i])}')

end_time = time.time()
diff = end_time - start_time
print(f' Code execution time is: {diff*1000} ms')

 The last number of 91239th Fibonacci number is: 6
 Code execution time is: 353.7604808807373 ms
 Multiple Tests: 
[5. 8. 9. 7. 8.]
 The last digit of 5.0th Fibonacci number is: 5
 The last digit of 8.0th Fibonacci number is: 1
 The last digit of 9.0th Fibonacci number is: 4
 The last digit of 7.0th Fibonacci number is: 3
 The last digit of 8.0th Fibonacci number is: 1
 Code execution time is: 0.0 ms


In [11]:
# Fibonacci Number: Tuple Unpacking, Multiple Assignment (Much Faster)
import numpy as np
import time
import sys

# Increase integer string conversion
sys.set_int_max_str_digits(1000000)

# Dashboard
num = 1000000 # still beyond 5 secs

# Multiple Assignment
def Fibonacci(n):
    a, b = 0, 1
    i = 0
    while i < n:
        a, b = b, a + b
        i+=1
    return str(a)[-1]
    
# Time your algorithm
start_time = time.time()

# Place the code here to be timed:
print(f' The last digit of {num}th Fibonacci number is: {Fibonacci(num)}')

end_time = time.time()
diff = end_time - start_time
print(f' Code execution time is: {diff*1000} ms')

# Create a for loop to generate multiple tests:
start_time = time.time()

# Place the code here to be timed:

print(f' Multiple Tests: ')
np.random.seed(5)
fibo_num_array = np.random.randint(2,10, 5).astype(float)
print(fibo_num_array)
for i in range(len(fibo_num_array)):
    print(f' The last digit of {fibo_num_array[i]}th Fibonacci number is: {Fibonacci(fibo_num_array[i])}')

end_time = time.time()
diff = end_time - start_time
print(f' Code execution time is: {diff*1000} ms')

 The last digit of 1000000th Fibonacci number is: 5
 Code execution time is: 8896.14987373352 ms
 Multiple Tests: 
[5. 8. 9. 7. 8.]
 The last digit of 5.0th Fibonacci number is: 5
 The last digit of 8.0th Fibonacci number is: 1
 The last digit of 9.0th Fibonacci number is: 4
 The last digit of 7.0th Fibonacci number is: 3
 The last digit of 8.0th Fibonacci number is: 1
 Code execution time is: 0.0 ms
